### ISSUE TITLE
Unknown option `--output-dir` with 3.4.1+

### ISSUE THREAD

**Issue by markwoon** [happo/happo-plugin-storybook#108]
After upgrading to 3.4.1 or 4.0 from 3.3.1, I'm getting:

```
 > yarn happo run
No [sha] provided. A temporary one will be used in place: "dev-3d643f9f96333f550e03".
(node:21412) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Generating static package...
error: unknown option '--output-dir'
✗
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:97:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

D:\...\node_modules\happo-plugin-storybook\index.js:97
        reject(new Error('Failed to build static storybook package'));
               ^
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:97:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by trotzig** [comment]
Hi @markwoon and thanks for the report! Thanks for trying different versions so that we can pinpoint this some more. It looks like we're detecting the wrong Storybook version for you. Are you on v6 or v7? 

The bug is somewhere in the `resolveBuildCommand` function: https://github.com/happo/happo-plugin-storybook/blob/6e02b978221ceb78333ccadf577943ab9adf89f3/index.js#L56

To help debug this, can you do the following and rerun on v4.0.0? 
- Set a `HAPPO_DEBUG=true` environment variable (e.g. on the command-line: `HAPPO_DEBUG=true yarn happo run`)
- Share your package.json file (send it via email to support@happo.io if you don't want to share publicly here)

Thanks!

**Comment by markwoon** [comment]
Running Storybook 7.6.8.

Testing with plugin v4.0.0 and `HAPPO_DEBUG=true` didn't provide any new info:
```
 > yarn happo run
No [sha] provided. A temporary one will be used in place: "dev-15d8c4fd9c8d7fa54458".
(node:8388) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Generating static package...
error: unknown option '--output-dir'
✗
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:135:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

D:\...\node_modules\happo-plugin-storybook\index.js:135
        reject(new Error('Failed to build static storybook package'));
               ^
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:135:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by trotzig** [comment]
Thanks for testing and for sending me the package.json file. Even though there are no debug logs from HAPPO_DEBUG it still gives us some information: 
A) There are only two code paths for `resolveBuildCommand` that result in no logs: 
- Either you have a `HAPPO_STORYBOOK_BUILD_COMMAND` environment variable configured (https://github.com/happo/happo-plugin-storybook/blob/6e02b978221ceb78333ccadf577943ab9adf89f3/index.js#L58)
- Or, we grab the version from your package.json file. I tried running the `getStorybookVersionFromPackageJson` function with your package.json file and it returns `7`, so I think we would end up here: https://github.com/happo/happo-plugin-storybook/blob/6e02b978221ceb78333ccadf577943ab9adf89f3/index.js#L66

The fact that it says "error: unknown option '--output-dir'" probable means we have resolved the wrong build command. If you install happo-plugin-storybook@4.0.1 and continue using `HAPPO_DEBUG=true`, there will be a log telling us what build command is used. Something like this:

```
[happo] Using build command `yarn storybook build --output-dir .happo-out --config-dir .storybook`
```

If you could make another attempt with the new version and share what you see, that would be very useful. 🙏

I should also mention that a simple workaround for you would probably be to set `HAPPO_STORYBOOK_BUILD_COMMAND="storybook build"`. The downside is that we never get to the bottom of why this is happening. 🙂

**Comment by markwoon** [comment]
With 4.0.1:

```
 > yarn happo run
No [sha] provided. A temporary one will be used in place: "dev-99f32fac2db0ba9a9f53".
(node:3984) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Generating static package...
[happo] Using build command `yarn storybook build --output-dir build/happo --config-dir .storybook`
error: unknown option '--output-dir'
✗
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:118:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

D:\...\node_modules\happo-plugin-storybook\index.js:118
        reject(new Error('Failed to build static storybook package'));
               ^
Error: Failed to build static storybook package
    at ChildProcess.<anonymous> (D:\...\node_modules\happo-plugin-storybook\index.js:118:16)
    at ChildProcess.emit (node:events:519:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

**Comment by trotzig** [comment]
Strange! It looks like we're detecting the right Storybook version (7) but for some reason the build command won't accept `--output-dir` even though it is supported (https://storybook.js.org/docs/api/cli-options#build). What happens if you run the command directly? `yarn storybook build --output-dir build/happo --config-dir .storybook`

**Comment by trotzig** [comment]
Oh, I just noticed that you have a `storybook` entry in the `scripts` section in your `package.json`. This is what's causing the issue with the unknown option. When we run `yarn storybook build` to build your project, we rely on this to invoke the `storybook` command in `./node_modules/.bin` but since you have that defined in package.json, it takes precedence. 

There are a few possible fixes to this as I see it: 
- You rename the `storybook` entry in package.json to something different
- You build the storybook yourself before running happo, and then set [`usePrebuiltPackage: true` in config](https://docs.happo.io/docs/storybook#options).
- We change the invocation use `./node_modules/.bin/storybook` instead of `yarn storybook`. 

Let me know what you think!

**Comment by markwoon** [comment]
I think it is common for people to have a `storybook` entry in package.json, so would suggest happo shouldn't rely on it.

Don't forget that this worked in 3.3.1, so something else must have changed so that this is breaking now?

In any case, I'm fine with building storybook myself and will use the `usePrebuildPackage` flag.

**Comment by trotzig** [comment]
Released a fix in https://github.com/happo/happo-plugin-storybook/releases/tag/v4.0.2. Give it a try and let me know if it works!

**Comment by markwoon** [comment]
Works without making any changes on my end.

Thanks!
